version: '3.8'
services:

  ############################## mosquitto
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./opt/mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001

  ############################## watchtower
  watchtower:
    image: containrrr/watchtower
    restart: always 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true" 


  ############################## modelserver
  modelserver:
    image: 2nfro/modelserver
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  