version: '3'
services:

  ############################## mosquitto
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./opt/mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      # you may set custom IP addresses
      myservers:
          ipv4_address: 172.16.238.77 
          ipv6_address: "2001:3984:3989::10"


  ############################## modelserver
  modelserver:
    image: siuwaikau/modelserver
    container_name: modelserver
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      # you may set custom IP addresses
      myservers:
          ipv4_address: 172.16.238.10 
          ipv6_address: "2001:3984:3989::10"



  ############################## watchtower
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_TRACE=true
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_HTTP_API_TOKEN=dckr_pat_K9eP1Ai8adPQ49CFeZLQmBnhNBg



networks:
    myservers:
        # use the bridge driver, but enable IPv6
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
                gateway: 172.16.238.1
                - subnet: "2001:3984:3989::/64"
                gateway: "2001:3984:3989::1"
  