version: '3'
services:

  ############################## mosquitto
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./opt/mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001


  ############################## modelserver
  modelserver:
    image: siuwaikau/modelserver
    container_name: modelserver
    labels:
      - "com.centurylinklabs.watchtower.enable=true"



  ############################## watchtower
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_TRACE=true
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_HTTP_API_TOKEN=dckr_pat_K9eP1Ai8adPQ49CFeZLQmBnhNBg


  