version: '3'
services:

  ############################## mosquitto
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./opt/mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001


  ############################## modelserver
  modelserver:
    image: siuwaikau/modelserver:latest
    container_name: modelserver


  ############################## watchtower
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8080:8080
    command: --interval 300 --cleanup --debug modelserver


  